dashboards/__init__.py
#!/usr/bin/python3
""" Flask application instance """

from flask import Flask
from flask_bcrypt import Bcrypt
from flask_login import LoginManager
from config import Config

bcrypt = Bcrypt()
login_manager = LoginManager()
login_manager.login_view = 'auth.login'
login_manager.login_message_category = 'info'


def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(Config)

    bcrypt.init_app(app)
    login_manager.init_app(app)

    from api import bp_api
    from dashboards.auth import bp_auth
    from dashboards.landing_page import bp_main
    from dashboards.administrator import bp_admin
    from dashboards.receptionist import bp_recep
    from dashboards.optometrist import bp_optom
    app.register_blueprint(bp_api)
    app.register_blueprint(bp_auth)
    app.register_blueprint(bp_main)
    app.register_blueprint(bp_admin)
    app.register_blueprint(bp_recep)
    app.register_blueprint(bp_optom)

    return app

dashboards/administrator/__init__.py
#!/usr/bin/python3
""" Blueprint for administrator """

from flask import Blueprint

bp_admin = Blueprint('admin', __name__)

from dashboards.administrator import routes

dashboards/administrator/routes.py
#!/usr/bin/python3
""" routes for admin """

from flask import render_template
from dashboards.administrator import bp_admin
from flask_login import current_user, login_required


@bp_admin.route("/admin", strict_slashes=False)
@login_required
def dashboard_admin():
    """ route for administrators dashboard """
    return render_template('admin.html')

dashboards/landing_page/__init__.py
#!/usr/bin/python3
""" Blueprint for main """

from flask import Blueprint

bp_main = Blueprint('main', __name__)

from dashboards.landing_page import routes

dashboards/landing_page/routes.py
#!/usr/bin/python3
""" routes for main """

from flask import render_template
from dashboards.landing_page import bp_main


@bp_main.route("/", strict_slashes=False)
@bp_main.route("/home", strict_slashes=False)
def home():
    """ route for homepage """
    return render_template('home.html', current_page='home')


@bp_main.route("/about", strict_slashes=False)
def about():
    """ route for about page """
    return render_template('about.html', current_page='about')


@bp_main.route("/contact", strict_slashes=False)
def contact():
    """ route for contact page """
    return render_template('contact.html', current_page='contact')

dashboards/optometrist/__init__.py
#!/usr/bin/python3
""" Blueprint for optometrist """

from flask import Blueprint

bp_optom = Blueprint('optom', __name__)

from dashboards.optometrist import routes

dashboards/optometrist/routes.py
#!/usr/bin/python3
""" routes for optometrists """

from flask import render_template
from dashboards.optometrist import bp_optom
from flask_login import login_required, current_user


@bp_optom.route("/optom", strict_slashes=False)
@login_required
def dashboard_optom():
    """" route for optometrist dashboard """
    return render_template('optom.html')

dashboards/receptionist/__init__.py
#!/usr/bin/python3
""" Blueprint for receptionist """

from flask import Blueprint

bp_recep = Blueprint('recep', __name__)

from dashboards.receptionist import routes

dashboards/receptionist/routes.py
#!/usr/bin/python3
""" routes for receptionist """

from flask import render_template
from dashboards.receptionist import bp_recep
from flask_login import login_required, current_user


@bp_recep.route("/recep", strict_slashes=False)
@login_required
def dashboard_recep():
    """ route for receptionist dashboard """
    return render_template('recep.html')

dashboards/templates/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles/header.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles/landing.css') }}">
    <link rel="icon" href="{{ url_for('static', filename='images/Logo.png') }}">
    <title>ClinicBase</title>
</head>
<body>
    <header>
        <nav class="navbar fixed-top navbar-expand-sm bg-turquoise navbar-light">
            <div class="container-fluid">
                <a class="navbar-brand" style="color: #333;" href="/">ClinicBase</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#collapsibleNavbar">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="collapsibleNavbar">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" style="color: #333;" href="{{ url_for('main.home') }}">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link {% if current_page == 'about' %}active{% endif %}" style="color: #333;" href="{{ url_for('main.about') }}">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" style="color: #333;" href="{{ url_for('main.contact') }}">Contact</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" style="color: #333;" href="{{ url_for('auth.login') }}">Dashboards</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <main class="container mt-3">
        <div class="row">
            <div class="col-md-12">
                <h3 class="mt-4">About ClinicBase DBMS</h3>
                <p class="text-justify">At ClinicBase, we're passionate about transforming healthcare in Ghana. Our state-of-the-art Database Management System (DBMS) is designed to optimize clinical operations for eye clinics, ENT clinics, and dental clinics.</p>
                <p class="text-justify">We tackle the challenge of fragmented data management, aiming to streamline workflows, improve data accuracy, enhance data security and privacy, enable data analytics, and ensure scalability. Our primary focus is on improving internal clinical workflows and data management, ultimately enhancing patient care and the efficiency of healthcare providers.</p>
                <p class="text-justify">While we don't provide patient dashboards or appointment booking through the web application, we empower healthcare professionals and patients by offering user-friendly department-specific dashboards for streamlined patient record management and medical data retrieval.</p>
                <p class="mb-4 text-justify">Join us in our mission to create a more efficient and secure healthcare system in Ghana. Contact us to learn more about ClinicBase DBMS and how it can empower your clinic.</p>
                <a href="{{ url_for('main.contact') }}" class="btn btn-primary">CONTACT US</a>
            </div>
        </div>
    </main>

    <footer class="mt-3 ml-3">
        <p style="padding-left: 20px;">Copyright &copy; <script>document.write(new Date().getFullYear())</script> ClinicBase</p>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
</body>
</html>

dashboards/templates/admin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/base.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/main.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/tab-links.css') }}">
    <link rel="icon" href="{{ url_for('static', filename='images/Logo.png') }}">
    <title>ClinicBase - Administrator</title>
</head>
<body>
    <header>
        <h1>ClinicBase</h1>
        <div id="api_status"></div>
        <nav class="logout">
            <ul>
                <li><a href="{{ url_for('auth.logout') }}">Logout</a></li>
                
            </ul>
        </nav>
    </header>
    <div class="container mt-3 ml-3">
        <div class="row">
            {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                     {{ message }}
                </div>
                {% endfor %}
            {% endif %}
            {% endwith %}
        </div>
    </div>
    <div class="container">
        <div class="employee-bar">
	    <div id="responseContainer">
	        <!-- CRUD Success Message -->
            </div>
            <div>
                <h4>Patient Count     <button id="patientCountBtn">Count Patients</button></h4>
                <h6 id="patientCount">Number: </h6> 
                
            </div>
            <div>
                <form>
                    <br>
                    <label for="startDate">Start Date:</label>
                    <input type="date" id="startDate" name="start_date" required><br><br>                                    
                    <label for="endDate">End Date:</label>
                    <input type="date" id="endDate" name="end_date" required><br><br>
                                
                    
                </form>

            </div>

            <div>
                <h4>Case Count     <button id="caseCountBtn">Count Cases</button></h4>
                <h6 id="caseCount"> Number: </h6>                
            </div>

        </div>

        <main>
            <section class="patient-status">
                <div>
                    <h4>Employee Section</h4>
                    <form id="searchEmployeeForm">
                        <label for="empSearchFilter">Search By:</label>
                        <select id="empSearchFilter" name="empSearchFilter" required>
                            <option value="name">Name</option>                            
                            <option value="email">Email</option>
                        </select><br><br>
                        <label for="empSearchText">Search Employee:</label><br>
                        <input type="text" id="empSearchText" name="empSearchText" placeholder="Enter search query"
                            required><br><br>
                        
                        <button type="submit">Search</button>
                    </form>
                    <h5>Search Results</h5>
		    <ul id="emp-radio-button-list">
                        <!-- Employee search will be added dynamically -->
                    </ul>
                    <button id="deleteEmployeeButton">Delete Employee</button>
                </div>
            </section>
            <section class="patient-info">
                <div class="patient-detail">

                </div>
                <div class="patient-history">

                    <div class="employee-tab">
                        <button class="tablinks" onclick="openTab(event, 'Add New Employee')" id="defaultOpen">Add New
                            Employee</button>
                        <button class="tablinks" onclick="openTab(event,'Update Employee Info')">Update Employee
                            Info</button>
                       
                    </div>
                    <div class="nav-content">
                        <form id="createEmployeeForm">
                            <div id="Add New Employee" class="tabcontent">
                                <h3>Add New Employee</h3>
                                <form id="createEmployeeForm">
                                    <label for="name">Name:</label>
                                    <input type="text" id="name" name="name" required><br><br>                                    
                                    <label for="email">Email:</label>
                                    <input type="email" id="email" name="email" required><br><br>
                                    <label for="password">Password:</label>
                                    <input type="password" id="password" name="password" required><br><br>                                
                                    <label for="role">Role:</label>
                                    <select id="role" name="role" required>
                                        <option value="optometrist">optometrist</option>
                                        <option value="receptionist">receptionist</option>
                                    </select><br><br>                                    
                                    <label for="licenseNumber">License Number:</label>
                                    <input type="text" id="licenseNumber" name="license"><br><br>
                                    <input type="submit" id="createEmployeeButton" value="Save Employee">
                                </form>
                            </div>
                            <div id="Update Employee Info" class="tabcontent">
                                <h3>Update Employee Info</h3>
                                <form id="updateEmployeeForm">                           
                                                                     
                                    <label for="email">Email:</label>
                                    <input type="email" id="uemail" name="email"><br><br>                                   
                                    <label for="psword">Password:</label>
                                    <input type="password" id="psword" name="password" required><br><br>
                                    <input type="submit" id="updateEmployeeButton" value="Update Employee">
                                </form>
                            </div>
                            

                        </form>

                    </div>

            </section>

            <section class="save-patient">
                <div>
                    <h4>Patient Section</h4>
                    <form id="searchPatientForm">
                        <label for="searchText">Search Patient:</label><br>
                        <input type="text" id="searchText" name="searchText" placeholder="Enter search query"
                            required><br><br>
                        <label for="searchFilter">Search Patient By:</label><br>
                        <select id="searchFilter" name="searchFilter" required>
                            <option value="firstname">First Name</option>
                            <option value="surname">Surname</option>
                            <option value="insurance">Insurance</option>
                        </select>
                        <button type="submit">Search</button>
                    </form>
                    <h5>Search Results</h5>
		    <ul id="radio-button-list">
                        <!-- Patient search will be added dynamically -->
                    </ul>
                </div>
                <button id="patientRecordButton">View Patient Records</button><br><br><br>
                <div id="medicalRecordsContainer">
                    <!-- Patient medical records will be added dynamically -->
                </div>
            </section>
        </main>
        
    </div>
    <footer>
        <p>Copyright &copy; <script>document.write(new Date().getFullYear())</script> ClinicBase</p>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    <script src="{{ url_for('static', filename='scripts/role.js') }}"></script>
    <script src="{{ url_for('static', filename='scripts/main.js') }}"></script>
    <script src="{{ url_for('static', filename='scripts/admin.js') }}"></script>
    <script src="{{ url_for('static', filename='scripts/medHist.js') }}"></script>
</body>
</html>

dashboards/templates/contact.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles/header.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles/landing.css') }}">
    <link rel="icon" href="{{ url_for('static', filename='images/Logo.png') }}">
    <title>ClinicBase</title>
</head>
<body>
    <header>
        <nav class="navbar fixed-top navbar-expand-sm bg-turquoise navbar-light">
            <div class="container-fluid">
                <a class="navbar-brand" style="color: #333;" href="/">ClinicBase</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#collapsibleNavbar">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="collapsibleNavbar">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" style="color: #333;" href="{{ url_for('main.home') }}">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" style="color: #333;" href="{{ url_for('main.about') }}">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link {% if current_page == 'contact' %}active{% endif %}" style="color: #333;" href="{{ url_for('main.contact') }}">Contact</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" style="color: #333;" href="{{ url_for('auth.login') }}">Dashboards</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <main class="container mt-3">
        <div class="row">
            <div class="col-md-12">
                <h3 class="mt-4">Contact ClinicBase</h3>
                <p class="text-justify">We'd love to hear from you! If you have any questions or would like to learn more about ClinicBase DBMS, please don't hesitate to get in touch with us.</p>
                <p class="text-justify">You can reach us through the following contact methods:</p>
                <ul>
                    <li>Email: <a href="mailto:tikolidavid@gmial.com">contact@clinicbase.com</a></li>
                    <li>Phone: +223-0262520270</li>
                </ul>
                <p class="text-justify">Our dedicated team is ready to assist you and provide information about how ClinicBase can benefit your clinic and improve your clinical operations.</p>
            </div>
        </div>
    </main>

    <footer class="mt-3 ml-3">
        <p style="padding-left: 20px;">Copyright &copy; <script>document.write(new Date().getFullYear())</script> ClinicBase</p>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
</body>
</html>

dashboards/templates/custom_404.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>404 - Page Not Found</title>
    <style>
        body {
            font-family: Arial, Helvetica, sans-serif;
            background-color: #f5f5f5;
            text-align: center;
            padding: 100px;
        }

        .container {
            background-color: #fff;
            border-radius: 5px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.2);
            padding: 20px;
        }

        h1 {
            color: #333;
        }

        p {
            color: #777;
        }

        .button {
            background-color: #007BFF;
            color: #fff;
            padding: 10px 20px;
            border: none;
            border-radius: 5px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            font-size: 16px;
            margin: 10px 2px;
            cursor: pointer;
        }

        .button:hover {
            background-color: #0056b3;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>404 - Page Not Found</h1>
        <p>The page you are looking for might have been removed, had its name changed, or is temporarily unavailable.</p>
        <a class="button" href="https://clinicbase.tech">Back to Home</a>
    </div>
</body>
</html>

dashboards/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles/header.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles/landing.css') }}">
    <link rel="icon" href="{{ url_for('static', filename='images/Logo.png') }}">
    <title>ClinicBase</title>
</head>
<body>
    <header>
        <nav class="navbar fixed-top navbar-expand-sm bg-turquoise navbar-light">
            <div class="container-fluid">
                <a class="navbar-brand" style="color: #333;" href="/">ClinicBase</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#collapsibleNavbar">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="collapsibleNavbar">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link {% if current_page == 'home' %}active{% endif %}" style="color: #333;" href="{{ url_for('main.home') }}">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" style="color: #333;" href="{{ url_for('main.about') }}">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" style="color: #333;" href="{{ url_for('main.contact') }}">Contact</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" style="color: #333;" href="{{ url_for('auth.login') }}">Dashboards</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <section class="hero">
        <div class="hero-image-container" style="background-image: url({{ url_for('static', filename='images/photo_1.jpg') }});">
            <div class="hero-content">
                <h2>Stay Proficient with ClinicBase</h2>
                <p>Track your Patients, monitor your cases, and retrieve records with ease.</p>
                <a href="{{ url_for('main.contact') }}" class="cta-button">Register Now</a>
            </div>
        </div>
    </section>
    <section class="features">
        <div class="container">
            <div class="gallery">
                <a  target="_self" href="{{ url_for('static', filename='images/photo_2.PNG') }}">
                    <img src="{{ url_for('static', filename='images/photo_2.PNG') }}" alt="Feature 1">
                </a>
                <div class="desc">
                    <h3>Track Patients</h3>
                    <p>Monitor your daily activities and see your progress over time.</p>
                </div>
            </div>
            <div class="gallery">
                <a href="{{ url_for('static', filename='images/photo_3.PNG') }}" target="_parent">
                    <img src="{{ url_for('static', filename='images/photo_3.PNG') }}" alt="Feature 2">
                </a>
                <div class="desc">
                    <h3>Manage Cases</h3>
                    <p>Streamline daily patient cases with no fuss</p>                   
                </div>
            </div>
            <div class="gallery">
                <a href="{{ url_for('static', filename='images/photo_4.PNG') }}" target="_self">
                    <img src="{{ url_for('static', filename='images/photo_4.PNG') }}" alt="Feature 3"></a>
                <div class="desc">
                    <h3>Retrieve Patient Info with Ease</h3>
                    <p>Patients record retrival have never been easy</p>
                </div>     
            </div>
        </div>
    </section>
    <section id="register" class="register">
        <div class="container">
            <h2>Get Started Today</h2>
	    <p>Use the Dashboards Tab to access a Demo Version of the ClinicBase Webapp. Login with the following Admin credentials to explore the functionalities of the application. Email: <strong>cbase_admin@gmail.com</strong>; Password: <strong>cbase_2023</strong>.</p>
            <p>Register with ClinicBase now and streamline your clinical work</p>
	    <a href="{{ url_for('main.contact') }}" class="cta-button">Get Started</a>
        </div>
    </section>
    <footer class="mt-3 ml-3">
        <p style="padding-left: 20px;">Copyright &copy; <script>document.write(new Date().getFullYear())</script> ClinicBase</p>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
</body>
</html>

dashboards/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles/header.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles/landing.css') }}">
    <link rel="icon" href="{{ url_for('static', filename='images/Logo.png') }}">
    <title>ClinicBase</title>
</head>
<body>
    <header>
        <nav class="navbar fixed-top navbar-expand-sm bg-turquoise navbar-light">
            <div class="container-fluid">
                <a class="navbar-brand" style="color: #333;" href="/">ClinicBase</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#collapsibleNavbar">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="collapsibleNavbar">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" style="color: #333;" href="{{ url_for('main.home') }}">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" style="color: #333;" href="{{ url_for('main.about') }}">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" style="color: #333;" href="{{ url_for('main.contact') }}">Contact</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link {% if current_page == 'login' %}active{% endif %}" style="color: #333;" href="{{ url_for('auth.login') }}">Login</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <main role="main">
        <div class="container mt-3 ml-3">
            <div class="row">
                <div class="col-md-8">
                    {% with messages = get_flashed_messages(with_categories=true) %}
                    {% if messages %}
                        {% for category, message in messages %}
                        <div class="alert alert-{{ category }}">
                            {{ message }}
                        </div>
                        {% endfor %}
                    {% endif %}
                    {% endwith %}
                </div>
            </div>
            <h3 class="mt-4">Login Here</h3>
            <form method="POST" action="" id="login" name="login">
                <div class="mb-3 mt-3">
                    <label for="email">Email:</label>
                    <input type="email" class="form-control col-6" id="email" placeholder="Enter email" name="email" required>
                </div>
                <div class="mb-3">
                    <label for="pwd">Password:</label>
                    <input type="password" class="form-control col-6" id="pwd" placeholder="Enter password" name="password" required>
                </div>
                <div class="form-check mb-3">
                    <label class="form-check-label">
                        <input class="form-check-input" type="checkbox" name="remember"> Remember me
                    </label>
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </main>
    <footer class="mt-3 ml-3">
        <p style="padding-left: 20px;">Copyright &copy; <script>document.write(new Date().getFullYear())</script> ClinicBase</p>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
</body>
</html>